export const enum ICON_NAME {
  ARTICLES = "articles",
  ARROW_LEFT = "arrow-left",

  INFO = "info",
  STAR = "star",
  SEARCH = "search",
  CLOSE = "close",

  // HOME = "home",
  // SEARCH = "search",
  // MENU = "menu",
  // CLOSE = "close",
  // BACK = "back",
  // FORWARD = "forward",

  // USER = "user",
  // LOGIN = "login",
  // LOGOUT = "logout",
  // PROFILE = "profile",
  // SETTINGS = "settings",
  // EDIT = "edit",
  // DELETE = "delete",

  // FACEBOOK = "facebook",
  // TWITTER = "twitter",
  // INSTAGRAM = "instagram",
  // LINKEDIN = "linkedin",
  // YOUTUBE = "youtube",
  // PINTEREST = "pinterest",

  // CART = "cart",
  // WISHLIST = "wishlist",
  // HEART = "heart",
  // TAG = "tag",
  // SALE = "sale",
  // CHECKOUT = "checkout",
  // DELIVERY = "delivery",

  // PLAY = "play",
  // PAUSE = "pause",
  // STOP = "stop",
  // VOLUME_UP = "volume-up",
  // VOLUME_DOWN = "volume-down",
  // MUTE = "mute",

  // CHAT = "chat",
  // MESSAGE = "message",
  // MAIL = "mail",
  // PHONE = "phone",
  // VIDEO_CALL = "video-call",
  // NOTIFICATION = "notification",

  // DOWNLOAD = "download",
  // UPLOAD = "upload",
  // ATTACHMENT = "attachment",
  // FILE = "file",
  // FOLDER = "folder",
  // SAVE = "save",

  // CALENDAR = "calendar",
  // CLOCK = "clock",
  // MAP = "map",
  // LOCATION = "location",
  // FILTER = "filter",
  // SORT = "sort",
  // REFRESH = "refresh",

  // CHECK = "check",
  // CROSS = "cross",
  // WARNING = "warning",
  // INFO = "info",
  // QUESTION = "question",
  // LOADER = "loader",
  // SUCCESS = "success",

  // STAR = "star",
  // THUMBS_UP = "thumbs-up",
  // THUMBS_DOWN = "thumbs-down",
  // LIKE = "like",
  // DISLIKE = "dislike",
}
